import { Chamado, Tecnico } from '../types/chamado';

export const INITIAL_TECNICOS: Tecnico[] = [
  // REDE
  {
    id: 1,
    nome: 'Roberto Redes',
    especialidade: 'REDE',
    cargaAtual: 1,
    capacidadeMax: 2,
    ativo: true,
  },
  {
    id: 2,
    nome: 'Renata Roteadores',
    especialidade: 'REDE',
    cargaAtual: 2,
    capacidadeMax: 4,
    ativo: true,
  },
  // HARDWARE
  {
    id: 3,
    nome: 'Hugo Hardware',
    especialidade: 'HARDWARE',
    cargaAtual: 1,
    capacidadeMax: 3,
    ativo: true,
  },
  {
    id: 4,
    nome: 'Helena Hard',
    especialidade: 'HARDWARE',
    cargaAtual: 0,
    capacidadeMax: 5,
    ativo: true,
  },
  // SOFTWARE
  {
    id: 5,
    nome: 'Sofia Software',
    especialidade: 'SOFTWARE',
    cargaAtual: 3,
    capacidadeMax: 4,
    ativo: true,
  },
  {
    id: 6,
    nome: 'Samuel Sistemas',
    especialidade: 'SOFTWARE',
    cargaAtual: 1,
    capacidadeMax: 2,
    ativo: true,
  },
  // ACESSO
  {
    id: 7,
    nome: 'Alice Acessos',
    especialidade: 'ACESSO',
    cargaAtual: 1,
    capacidadeMax: 3,
    ativo: true,
  },
  {
    id: 8,
    nome: 'Arthur Autenticação',
    especialidade: 'ACESSO',
    cargaAtual: 2,
    capacidadeMax: 6,
    ativo: true,
  },
];

const now = new Date();
const hoursAgo = (h: number) => new Date(now.getTime() - h * 60 * 60 * 1000).toISOString();
const hoursFromNow = (h: number) => new Date(now.getTime() + h * 60 * 60 * 1000).toISOString();

export const INITIAL_CHAMADOS: Chamado[] = [
  {
    id: 'c-101',
    usuarioId: 'user-fatec-1',
    titulo: 'Queda de conexão no Bloco B',
    descricao: 'Os switches do segundo andar pararam de responder após oscilação de energia.',
    categoria: 'REDE',
    prioridade: 'CRITICA',
    status: 'EM_ATENDIMENTO',
    protocolo: 'CH-2026-000101',
    tecnicoId: 1,
    tecnicoNome: 'Roberto Redes',
    slaPrazo: hoursFromNow(2.5),
    criadoEm: hoursAgo(1.5),
    historico: [
      {
        id: 'h-1',
        chamadoId: 'c-101',
        statusAnterior: null,
        statusNovo: 'ABERTO',
        data: hoursAgo(1.5),
        observacao: 'Chamado aberto pelo usuário. Evento ChamadoAbertoEvent registrado no Outbox.',
      },
      {
        id: 'h-2',
        chamadoId: 'c-101',
        statusAnterior: 'ABERTO',
        statusNovo: 'EM_ATENDIMENTO',
        data: hoursAgo(1.4),
        observacao: 'Consumo do evento RabbitMQ pelo atendimento-service. Técnico Roberto Redes atribuído. Protocolo CH-2026-000101 gerado com SLA de 4 horas.',
      },
    ],
  },
  {
    id: 'c-102',
    usuarioId: 'user-fatec-1',
    titulo: 'Instalação do Docker e JDK 21 no Lab 04',
    descricao: 'Necessário preparar as máquinas para a aula prática de microsserviços.',
    categoria: 'SOFTWARE',
    prioridade: 'MEDIA',
    status: 'EM_ATENDIMENTO',
    protocolo: 'CH-2026-000102',
    tecnicoId: 6,
    tecnicoNome: 'Samuel Sistemas',
    slaPrazo: hoursFromNow(18),
    criadoEm: hoursAgo(6),
    historico: [
      {
        id: 'h-3',
        chamadoId: 'c-102',
        statusAnterior: null,
        statusNovo: 'ABERTO',
        data: hoursAgo(6),
        observacao: 'Chamado cadastrado no sistema (Status 202 Accepted).',
      },
      {
        id: 'h-4',
        chamadoId: 'c-102',
        statusAnterior: 'ABERTO',
        statusNovo: 'EM_ATENDIMENTO',
        data: hoursAgo(5.9),
        observacao: 'Técnico Samuel Sistemas (menor carga em SOFTWARE) alocado. SLA definido para 24 horas.',
      },
    ],
  },
  {
    id: 'c-103',
    usuarioId: 'user-fatec-1',
    titulo: 'Reset de credenciais de VPN corporativa',
    descricao: 'Não consigo autenticar na VPN após expiração da senha temporária.',
    categoria: 'ACESSO',
    prioridade: 'ALTA',
    status: 'RESOLVIDO',
    protocolo: 'CH-2026-000098',
    tecnicoId: 7,
    tecnicoNome: 'Alice Acessos',
    slaPrazo: hoursAgo(2),
    criadoEm: hoursAgo(10),
    historico: [
      {
        id: 'h-5',
        chamadoId: 'c-103',
        statusAnterior: null,
        statusNovo: 'ABERTO',
        data: hoursAgo(10),
        observacao: 'Chamado aberto pelo portal.',
      },
      {
        id: 'h-6',
        chamadoId: 'c-103',
        statusAnterior: 'ABERTO',
        statusNovo: 'EM_ATENDIMENTO',
        data: hoursAgo(9.9),
        observacao: 'Técnica Alice Acessos assumiu o chamado.',
      },
      {
        id: 'h-7',
        chamadoId: 'c-103',
        statusAnterior: 'EM_ATENDIMENTO',
        statusNovo: 'RESOLVIDO',
        data: hoursAgo(4),
        observacao: 'Senha provisória enviada e autenticação em dois fatores restabelecida.',
      },
    ],
  },
  {
    id: 'c-104',
    usuarioId: 'user-fatec-1',
    titulo: 'Monitor piscando e sem sinal HDMI',
    descricao: 'Monitor Dell 27 polegadas da estação 12 desliga intermitentemente.',
    categoria: 'HARDWARE',
    prioridade: 'BAIXA',
    status: 'AGUARDANDO_TECNICO',
    protocolo: null,
    tecnicoId: null,
    tecnicoNome: null,
    slaPrazo: null,
    criadoEm: hoursAgo(0.5),
    historico: [
      {
        id: 'h-8',
        chamadoId: 'c-104',
        statusAnterior: null,
        statusNovo: 'ABERTO',
        data: hoursAgo(0.5),
        observacao: 'Chamado registrado com sucesso.',
      },
      {
        id: 'h-9',
        chamadoId: 'c-104',
        statusAnterior: 'ABERTO',
        statusNovo: 'AGUARDANDO_TECNICO',
        data: hoursAgo(0.48),
        observacao: 'Fila de espera ativada (atribuicao.falhou). Aguardando liberação de capacidade dos técnicos de Hardware.',
      },
    ],
  },
];
