server.port=8083

spring.application.name=login-service

# Banco de Dados H2 isolado
spring.datasource.url=jdbc:h2:mem:logindb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console Web
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Segredo JWT (Deve ser idêntico ao JWT_SECRET configurado no GATEWAY)
jwt.secret=minha-chave-secreta-super-segura-jwt-fatec-2026-com-ao-menos-256-bits!
jwt.expiration-ms=86400000

management.endpoints.web.exposure.include=health,info
